---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vpc/vars/vpc.yml
  tasks:
    - include: vpc/tasks/vpc.yml



# Create the VPC
#  tasks:
#    - name : Creating AWS VPC
#      ec2_vpc:
#        state: present
#        cidr_block: 10.0.0.0/16
#        resource_tags: { "Environment":"Staging" }
#        subnets:
#          - cidr: 10.0.0.0/24
#            az: us-west-2c
#            resource_tags: { "Environment":"Staging", "Tier" : "DB" }
#            internet_gateway: True
#        region: us-west-2
#      register: vpc



#  tasks:
#    - name: Provisioning a New stock instance
#      ec2:
#        key_name: "{{ default_key_name }}"
#        group: "{{ default_security_group }}"
#        instance_type: "{{ default_instance_type }}"
#        image: "{{ default_image }}"
#        wait: true
#        region: "{{ default_region }}"  
#        assign_public_ip: yes      
#        instance_tags:
#          Name: test-server
#        vpc_subnet_id: "{{ default_subnet_id }}"

#      register: ec2

#    - name: Record Web server instance public IPs to host group
#      add_host: hostname={{ item.public_ip }} groups=testservers
#      with_items: ec2.instances

#    - name: Wait for Web server SSH connectivity
#      wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
#      with_items: ec2.instances



