---

- name: Creating Mysql server security group
  local_action:
    module: ec2_group
    name: "{{ item.location }}-mysql-sg"
    description: "Mysql master security group"
    region: "{{ item.region }}" 
    vpc_id: "{{ lookup('file', 'vpc/vars/' + item.region + '-vpc-info.yml') }}"
    state: present
    rules: "{{ sg_rules }}"
  register: mysql_sg         
  with_items: 
    - "{{ mysql_vpcs }}"


- name: Saving Security group ids
  shell: echo "{{ item.group_id }}" > "{{ item.invocation.module_complex_args.region }}-sg-info.yml"
  args:
    chdir: security_groups/vars/
  with_items: 
    - "{{ mysql_sg.results }}"
