---
# Ensure that you do not use the tag "Environment" as its a reserved word.
# I have used "Env" instead

- name: Creating VPC to host Mysql servers
  local_action: 
    module: ec2_vpc
    region: "{{ item.region }}"
    state: present
    cidr_block: "{{ item.cidr }}/16"
    resource_tags: {"Name":"{{ item.location }}_mysql_vpc", "Env":"{{ env }}"}  
    subnets:
      - cidr: "{{ item.cidr }}/24"
        az: "{{ item.region }}a"
        resource_tags: { "Name":"{{ subnet_name }}","Env":"{{ env }}","Tier":"{{ subnet_tier }}" }
        internet_gateway: True 
    internet_gateway: yes
    route_tables: 
      - subnets:
          - "{{ item.cidr }}/24"
        routes:
          - dest: 0.0.0.0/0
            gw: igw
  register: "vpc"
  with_items: 
    - "{{ mysql_vpcs }}"



- name: Saving VPC ids
  shell: echo "{{ item.vpc_id }}" > "{{ item.vpc.region }}-vpc-info.yml"
  args:
    chdir: vpc/vars/
  with_items: 
    - "{{ vpc.results }}"
  

- name: Saving Subnet id
  shell: echo "{{ item.subnets[0].id }}" > "{{ item.vpc.region }}-subnet-info.yml"
  args:
    chdir: vpc/vars/
  with_items: 
    "{{ vpc.results }}"

#- name: Saving Subnet and VPC ids as facts
#  set_fact:
#    vpc_id: "{{ lookup('file', 'vpc/vars/' + vpc_name + '_info.yml') }}"
#    vpc_subnet_id: "{{ lookup('file', 'vpc/vars/' + subnet_name + '_info.yml') }}"