---
- name: Creating the Mysql Instance(s)
  local_action:
    module: ec2
    region: "{{ item.region }}"
    group: "{{ item.location }}-mysql-sg"
    keypair: "ansible-{{ item.location }}-keypair"
    instance_type: "{{ mysql_instance_type }}"
    image: "{{ item.ami }}"
    vpc_subnet_id: "{{ lookup('file', 'vpc/vars/' + item.region + '-subnet-info.yml') }}"
    assign_public_ip: True
    wait: True
    wait_timeout: 600
    instance_tags:
      Name: "master_{{ item.location }}"
      Env: "{{ env }}"
  register: mysql_master
  with_items: 
    - "{{ mysql_vpcs }}"

- name: Adding the mysql host details
  local_action: 
    module: lineinfile 
    dest: "./hosts" 
    insertafter: "[mysql]" 
    line: "master_{{ item.item.location }} ansible_ssh_private_key_file=/etc/ansible/keys/ansible-{{ item.item.location }}-keypair.pem ansible_ssh_host={{ item.instances[0].public_ip }}" 
  with_items:
    - "{{ mysql_master.results }}"

- name: Waiting for SSH confirmation
  local_action: 
    module: wait_for 
    host: "{{ item.instances[0].public_ip }}" 
    port: 22 
    state: started
  with_items: 
    - "{{ mysql_master.results }}"

- name: Adding SSH group
  add_host: 
    hostname: "master_{{ item.item.location }}"
    host_location: "{{ item.item.location }}"
    ansible_ssh_private_key_file: "/etc/ansible/keys/ansible-{{ item.item.location }}-keypair.pem"
    ansible_ssh_host: "{{ item.instances[0].public_ip }}"       
    groupname: mysql
  with_items: 
   - "{{ mysql_master.results }}"


- name: Adding the master details
  shell: echo "{{ item.instances[0].public_ip }}" > "master_of_{{ slave_maps[item.item.location] }}"
  args:
    chdir: db/vars/
  with_items:
    - "{{ mysql_master.results }}"   
